name = "Bear House"
license = "MIT"
licenselink = "https://github.com/akku1139/hugo-bearhouse/blob/main/LICENSE"
description = "A lightweight Hugo theme based on Bear Blog, Hugo Bear Blog and Hugo Bear Cub. It is free, multilingual, optimized for search engines, no-nonsense, responsive, light, and fast. Really fast."

# The home page of the theme, where the source can be found.
homepage = "https://github.com/akku1139/hugo-bearhouse"

# If you have a running demo of the theme.
# demosite = "https://clente.github.io/hugo-bearcub"

tags = ["blog", "responsive", "minimal", "personal", "dark", "multilingual"]
features = ["favicon", "seo", "no javascript", "rss", "social cards"]

# If the theme has a single author
[author]
    name = "akku"
    homepage = "https://akku1139.github.io/"

# If porting an existing theme
[original]
    name = "Caio Lente"
    homepage = "https://lente.dev"
    repo = "https://github.com/clente/hugo-bearcub

# Hugo versions the theme supports
[module]
  [module.hugoVersion]
    min = "0.90"
